### ISSUE TITLE
Conflicts with multiple instances

### ISSUE THREAD

**Issue by ProMix0** [coffebar/hyprland-per-window-layout#3]
**Describe the bug**
When exiting and starting Hyprland again new instance of the plugin will be started. It highly increases CPU usage, maybe due to some kind of resource race

**To Reproduce**
1. Configure plugin and Hyprland as described in README
2. Close Hyperland session and run it again a few times
3. Check processes using `top` or your preferred way

  
![image](https://user-images.githubusercontent.com/54300969/227644649-63287109-b187-47e4-bde9-868fb3f7c388.png)

**Expected behavior**
Avoiding multiple instance running. Or, at least, consuming less CPU

**Linux Distro (please complete the following information):**
 - Arch with latest updates
 - Hyprland, hyprland-per-window-layout

**Additional context**
There is a workaround for this bug:
`exec-once = killall hyprland-per-window-layout; hyprland-per-window-layout`

**Comment by coffebar** [comment]
I think this will be fixed, but anyways, starting multiple instances on the app is not the problem of the app. You should configure your Hyprland startup another way because you will have such problems with other apps, even if you're not seeing this right now. 
For me, Hyprland session work with user session, so when Hyprland session is over - all programs started by user are closed.

**Comment by coffebar** [comment]
since v2.2 it's not allowed to start multiple instances.
